services:
  - type: web
    name: apexpay-core-web
    env: python
    pythonVersion: 3.12.7   
    region: oregon
    plan: free
    branch: main
    buildCommand: >
      pip install -r requirements.txt &&
      python manage.py migrate &&
      python manage.py collectstatic --noinput
    startCommand: gunicorn apexpay_core.wsgi:application --bind 0.0.0.0:$PORT
    autoDeploy: true
    envVars:
      - key: PYTHONUNBUFFERED
        value: '1'
